/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.conspref.consprefbe.util;

public enum E_ERRORI {

	SERVICE_REQ_MISSING("CONS.E00"),
	CONSENSO_ALREADY_FOUND("CONS.E01"),
	RICHIEDENTE_MISSING("CONS.E02"),
	CF_RICHIEDENTE_MISSING("CONS.E03"),
	SERVIZIO_RICHIEDENTE_MISSING("CONS.E04"),
	ID_REQUEST_RICHIEDENTE_MISSING("CONS.E05"),
	COD_SERVIZIO_RICHIEDENTE_MISSING("CONS.E06"),
	NOTIFICATORE_ERROR("CONS.E08"),
	NOT_UNIQUE_RESULT("CONS.E09"),
	NO_OCCURRENCE("CONS.E10"),
	
	CF_CITTADINO_MISSING("CONS.0001"),
	CF_CITTADINO_AURA_MISSING("CONS.0002"),
	CF_DELEGATO_WRONG("CONS.0003"),
	OPERATORE_WRONG("CONS.0004"),
	D_ACQUISIZIONE_MISSING("CONS.0005"),
	D_ACQUISIZIONE_WRONG("CONS.0006"),
	COD_TIPO_FONTE_WRONG("CONS.0007"),
	COD_FONTE_WRONG("CONS.0008"),
	TIPO_CONSENSO_MISSING("CONS.0009"),
	SOTTOTIPO_CONSENSO_MISSING("CONS.0010"),
	TIPO_CONSENSO_WRONG("CONS.0011"),
	SOTTOTIPO_CONSENSO_WRONG("CONS.0012"),
	TIPO_FONTE_MISSING("CONS.0013"),
	COD_ASR_MISSING("CONS.0014"),
	CONSENSO_RIFIUTATO("CONS.0015"),
	INFORMATIVA_MISSING("CONS.0016"),
	CF_CITTADINO_WRONG("CONS.0017"),
	CF_EQUALS("CONS.0018"),
	ID_AURA_MISSING("CONS.0019"),
	
	NOT_UNIQUE_RESULT_CODE("CONS.R01"),
	NO_RESULT_CODE("CONS.R02"),
	FONTE_NON_PREVISTA("CONS.R03"),
	OPERATORE_NON_PREVISTO("CONS.R04"),
	TIPO_STATO_NON_PREVISTO("CONS.R05"),
	TIPO_CONSENSO_NON_PREVISTO("CONS.R06"),
	TIPO_FONTE_NON_PREVISTA("CONS.R07"),
	VALORE_NON_PREVISTO("CONS.R08"),
	NO_RESULT_ID("CONS.R09"),
	SOTTOTIPO_CONSENSO_NON_PREVISTO("CONS.R10"),
	AURA_NOT_AVAILABLE("CONS.R11"),
	
	
	R_CF_RICHIEDENTE_MISSING("ERR_0001"),
	R_CF_RICHIEDENTE_WRONG("ERR_0002"),
	R_CF_DELEGATO_WRONG("ERR_0004"),
	R_TIPO_OPERATORE_MISSING("ERR_0006"),
	R_CODICE_OPERATORE_MISSING("ERR_0007"),
	R_TIPO_OPERATORE_WRONG("ERR_0008"),
	R_CODICE_OPERATORE_WRONG("ERR_0009"),
	R_CODICE_TIPO_FONTE_MISSING("ERR_0010"),
	R_CODICE_FONTE_MISSING("ERR_0011"),
	R_CODICE_TIPO_FONTE_WRONG("ERR_0012"),
	R_CODICE_FONTE_WRONG("ERR_0013"),
	R_DATA_ACQUISIZIONE_MISSING("ERR_0014"),
	R_DATA_ACQUISIZIONE_WRONG("ERR_0015"),
	R_CODICE_TIPO_CONSENSO_MISSING("ERR_0016"),
	R_CODICE_TIPO_CONSENSO_WRONG("ERR_0017"),
	R_CODICE_SOTTOTIPO_CONSENSO_MISSING("ERR_0018"),
	R_CODICE_SOTTOTIPO_CONSENSO_WRONG("ERR_0019"),
	R_DESC_SOTTOTIPO_CONSENSO_MISSING("ERR_0020"),
	R_DESC_SOTTOTIPO_CONSENSO_WRONG("ERR_0021"),
	R_VALORE_CONSENSO_MISSING("ERR_0022"),
	R_VALORE_CONSENSO_WRONG("ERR_0023"),
	R_CODICE_ASR_MISSING("ERR_0024"),
	R_CODICE_ASR_WRONG("ERR_0025"),
	R_CODICE_ASR_REGIONE("ERR_0026"),
	R_ID_AURA_MISSING("ERR_0027"),
	R_ID_AURA_WRONG("ERR_0028");
			
			
	
	private E_ERRORI(String code) {
		this.code = code;
	}
	
	public String  getErrorCode() {
    return this.code;
	}
	
	private String code;
	
}
